# Generated by Django 6.0 on 2026-01-04 16:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanproduct_loanschedule_alter_loan_options_and_more'),
        ('repayments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('reversed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='repayment',
            options={'ordering': ['-paid_on', '-created_at']},
        ),
        migrations.AddField(
            model_name='repayment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repayment',
            name='fees_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='repayment',
            name='interest_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='repayment',
            name='penalty_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='repayment',
            name='principal_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='repayment',
            name='receipt_number',
            field=models.CharField(default='TEMP', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repayment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repayment',
            name='received_on',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When payment was received/recorded'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('reversed', 'Reversed')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='loans.loan'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('direct_debit', 'Direct Debit')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='reference',
            field=models.CharField(blank=True, default='', help_text='Transaction reference/cheque number', max_length=100),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['receipt_number'], name='repayments__receipt_74c51e_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['loan', 'paid_on'], name='repayments__loan_id_856cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['status'], name='repayments__status_8bb44a_idx'),
        ),
        migrations.AddField(
            model_name='paymentreversal',
            name='repayment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reversals', to='repayments.repayment'),
        ),
        migrations.AddField(
            model_name='paymentreversal',
            name='reversed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
