# Generated by Django 6.0 on 2026-01-04 16:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, help_text='Residential/Business address'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='TEMP', editable=False, help_text='Auto-generated ID', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group/Solidarity'), ('sme', 'Small/Medium Enterprise')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='employer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='ghana_card_id',
            field=models.CharField(blank=True, help_text='Ghana Card Number (masked)', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='group_leader',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='group_size',
            field=models.PositiveIntegerField(blank=True, help_text='Number of members in group', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='kyc_verified',
            field=models.BooleanField(default=False, help_text='KYC documents verified'),
        ),
        migrations.AddField(
            model_name='client',
            name='kyc_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='kyc_verified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated monthly income in GHS', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='risk_category',
            field=models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('blacklisted', 'Blacklisted')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+233XXXXXXXXX'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_id'], name='clients_cli_client__a44f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['ghana_card_id'], name='clients_cli_ghana_c_0b00b8_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='clients_cli_status_ce0d15_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['risk_category'], name='clients_cli_risk_ca_f9ce6c_idx'),
        ),
    ]
