# Generated by Django 6.0 on 2026-01-04 16:42

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_client_address_client_client_id_and_more'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Product name (e.g., 'Individual Micro Loan')", max_length=100)),
                ('code', models.CharField(help_text="Product code (e.g., 'IML-001')", max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('interest_method', models.CharField(choices=[('flat', 'Flat Rate'), ('declining', 'Declining Balance'), ('compound', 'Compound Interest')], default='declining', max_length=20)),
                ('min_term_months', models.PositiveIntegerField(default=3)),
                ('max_term_months', models.PositiveIntegerField(default=24)),
                ('repayment_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('bullet', 'Bullet (End of Term)')], default='monthly', max_length=20)),
                ('processing_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='% of principal', max_digits=5)),
                ('insurance_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% of principal', max_digits=5)),
                ('late_payment_penalty_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='% per month overdue', max_digits=5)),
                ('requires_collateral', models.BooleanField(default=False)),
                ('requires_guarantor', models.BooleanField(default=True)),
                ('min_guarantors', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('penalty_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('penalty_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, help_text='Remaining balance for this installment', max_digits=12)),
                ('principal_balance', models.DecimalField(decimal_places=2, help_text='Outstanding principal after this installment', max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('days_late', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['loan', 'installment_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='loan',
            name='application_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='classification',
            field=models.CharField(choices=[('current', 'Current (0-30 days)'), ('substandard', 'Substandard (31-90 days)'), ('doubtful', 'Doubtful (91-180 days)'), ('loss', 'Loss (>180 days)')], default='current', help_text='BoG loan classification', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='days_in_arrears',
            field=models.IntegerField(default=0, help_text='Days overdue'),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_method',
            field=models.CharField(blank=True, help_text='Cash, Bank Transfer, Mobile Money', max_length=50),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='loan',
            name='first_repayment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Regular installment amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='insurance_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_method',
            field=models.CharField(choices=[('flat', 'Flat Rate'), ('declining', 'Declining Balance'), ('compound', 'Compound Interest')], default='declining', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(default='TEMP', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='maturity_date',
            field=models.DateField(blank=True, help_text='Expected final payment date', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('bullet', 'Bullet (End of Term)')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total interest over loan term', max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_repayable',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Principal + Interest', max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active/Disbursed'), ('closed', 'Closed/Paid Off'), ('written_off', 'Written Off')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.loanproduct'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_id'], name='loans_loan_loan_id_4268fd_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='loans_loan_status_962e99_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['classification'], name='loans_loan_classif_309e06_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['disbursed_date'], name='loans_loan_disburs_ce61e0_idx'),
        ),
        migrations.AddField(
            model_name='loanschedule',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='loans.loan'),
        ),
        migrations.AddIndex(
            model_name='loanschedule',
            index=models.Index(fields=['loan', 'due_date'], name='loans_loans_loan_id_b2d3df_idx'),
        ),
        migrations.AddIndex(
            model_name='loanschedule',
            index=models.Index(fields=['due_date'], name='loans_loans_due_dat_dbcf1e_idx'),
        ),
        migrations.AddIndex(
            model_name='loanschedule',
            index=models.Index(fields=['is_paid'], name='loans_loans_is_paid_08cd71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loanschedule',
            unique_together={('loan', 'installment_number')},
        ),
    ]
